nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.1.cjs

# 设置Node.js版本
nodeVersion: "22.16.0"

# 启用零安装模式
enableGlobalCache: true

# 设置包管理器
packageManager: "yarn@4.9.1"

# 强制使用Yarn
preferInteractive: false
enableGlobalCache: false 