name = "my-cloudflare-docker-proxy"
compatibility_date = "2024-12-01"
main = "src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "workers.dev"
MODE = "production"
TARGET_UPSTREAM = ""

[env.production]
name = "my-cloudflare-docker-proxy"
CUSTOM_DOMAIN = "workers.dev"
MODE = "production"
TARGET_UPSTREAM = ""

[build]
command = "npm run build" 